name: Deploy to itch.io

on:
  workflow_dispatch: 
  push:
    branches:
      - main

permissions: {}

jobs:
  build-and-upload:
    uses: ./.github/workflows/build-webgl.yml
    with:
      itch-user: kertic
      itch-game: critterchronicles
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
