# .github/workflows/webgl-to-itch.yml
name: Build WebGL and Upload to itch.io

on:
  push:
    branches:
      - main

jobs:
  build-webgl:
    runs-on: ubuntu-latest

    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

      ITCH_USER: kertic
      ITCH_GAME: critterchronicles
      ITCH_CHANNEL: html5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-WebGL-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-WebGL-

      - name: Build Unity WebGL
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL

      - name: Download butler
        run: |
          curl -L -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip -d butler
          chmod +x butler/butler

      - name: Upload WebGL build to itch.io
        run: |
          ./butler/butler push "build/WebGL/WebGL" "$ITCH_USER/$ITCH_GAME:$ITCH_CHANNEL"
